export const CATEGORY_IMAGES = {
  smartphones: "https://i.dummyjson.com/data/products/2/1.jpg",
  laptops: "https://i.dummyjson.com/data/products/7/1.jpg",
  fragrances: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
  skincare: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
  groceries: "https://i.dummyjson.com/data/products/21/thumbnail.png",
  homedecoration: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
  furniture: "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
  tops: "https://i.dummyjson.com/data/products/36/thumbnail.jpg",
  womensdresses: "https://i.dummyjson.com/data/products/41/thumbnail.webp",
  womensshoes: "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
  mensshirts: "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
  mensshoes: "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
  menswatches: "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
  womenswatches: "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
  womensbags: "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
  womensjewellery: "https://i.dummyjson.com/data/products/76/thumbnail.jpg",
  sunglasses: "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
  automotive: "https://i.dummyjson.com/data/products/86/thumbnail.jpg",
  motorcycle: "https://i.dummyjson.com/data/products/91/thumbnail.jpg",
  lighting: "https://i.dummyjson.com/data/products/96/thumbnail.jpg",
};
